# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.version.version

'1.23.1'

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [6]:
np.size(null_vector)

10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
null_vector2 = np.zeros(10)
null_vector2[4] = 1
null_vector2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
vector3 = np.arange(10,50)
vector3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [11]:
vector3[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [13]:
vector4 = [1,2,0,0,4,0]
np.nonzero(vector4)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [15]:
np.random.random((3,3,3))

array([[[0.73506851, 0.15689758, 0.04088035],
        [0.2958552 , 0.2374424 , 0.17494534],
        [0.50615827, 0.75526847, 0.93106099]],

       [[0.20351527, 0.17615429, 0.85231012],
        [0.46058114, 0.38384479, 0.25111359],
        [0.69091231, 0.34434192, 0.62514249]],

       [[0.01507748, 0.33039274, 0.09833184],
        [0.11650845, 0.5829525 , 0.32311047],
        [0.54327304, 0.8854429 , 0.67149166]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [17]:
array1 = np.random.random((10,10))
array1, np.min(array1), np.max(array1)

(array([[0.56244509, 0.57193245, 0.14541214, 0.69089944, 0.52922383,
         0.08811271, 0.6713389 , 0.63190412, 0.38106268, 0.85988466],
        [0.82940357, 0.63365352, 0.98959459, 0.22491562, 0.6330251 ,
         0.49378303, 0.8579118 , 0.66714496, 0.13386362, 0.78913124],
        [0.97536529, 0.91620564, 0.87042415, 0.41124619, 0.00701321,
         0.09763555, 0.71870001, 0.57147062, 0.82713182, 0.61711453],
        [0.10116882, 0.22120904, 0.87644234, 0.0203563 , 0.26552403,
         0.90397744, 0.20066317, 0.24212474, 0.93221907, 0.29438833],
        [0.70372849, 0.78447237, 0.56224246, 0.32297765, 0.94110527,
         0.1511592 , 0.35324943, 0.40933949, 0.763965  , 0.24186845],
        [0.78393564, 0.87523036, 0.20044129, 0.8339645 , 0.71534925,
         0.17983281, 0.99747737, 0.63488504, 0.6338195 , 0.97667669],
        [0.16054647, 0.16567702, 0.6729074 , 0.63598591, 0.59798017,
         0.79841   , 0.25869301, 0.16654659, 0.64692319, 0.47605544],
        [0.03418635, 0.9702

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [18]:
vector5 = np.random.random(30)
vector5, np.mean(vector5)

(array([0.72680721, 0.80193675, 0.92435941, 0.5664023 , 0.58401388,
        0.25642231, 0.26635049, 0.27878116, 0.18942293, 0.50308993,
        0.96189632, 0.37820397, 0.57176625, 0.37499107, 0.96947906,
        0.65073792, 0.4486045 , 0.23547128, 0.45316878, 0.0846509 ,
        0.08774107, 0.88740928, 0.62617636, 0.16149193, 0.15645005,
        0.84705414, 0.98730036, 0.67456219, 0.51517513, 0.77005572]),
 0.5313324227988334)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [22]:
array2 = np.ones((3,3))
array2[1,1] = 0
array2

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [24]:
array3 = np.ones((2,2))
np.pad(array3,pad_width=1,mode="constant",constant_values=0)

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [29]:
0 * np.nan, np.nan == np.nan, np.inf > np.nan, np.nan - np.nan, np.nan in set([np.nan]), 0.3 == 3 * 0.1

(nan, False, False, nan, True, False)

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [30]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [32]:
matrix1 = np.ones((8,8))
matrix1[::2,1::2] = 0
matrix1[1::2,::2] = 0
matrix1

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [33]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [37]:
np.tile([0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0],4).reshape(8,8)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [39]:
matrix2 = np.random.random((5,5))
normalize_matrix2 = matrix2 / np.linalg.norm(matrix2,axis=1)
matrix2,normalize_matrix2

(array([[0.45721207, 0.60474867, 0.81280497, 0.20140542, 0.06430546],
        [0.24931525, 0.2101199 , 0.21744145, 0.64293189, 0.36629004],
        [0.06625533, 0.77019841, 0.26151736, 0.71036344, 0.23323818],
        [0.17608803, 0.93679563, 0.65441981, 0.81413477, 0.94108578],
        [0.19463088, 0.13842213, 0.38002068, 0.56803843, 0.8075036 ]]),
 array([[0.40410403, 0.72223583, 0.73437483, 0.1185699 , 0.05929385],
        [0.22035572, 0.25094082, 0.19645983, 0.37850207, 0.3377434 ],
        [0.05855936, 0.91982821, 0.23628271, 0.41819987, 0.21506087],
        [0.15563431, 1.11879101, 0.59127276, 0.47929135, 0.86774269],
        [0.17202328, 0.165314  , 0.34335127, 0.33441135, 0.74457119]]))

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [40]:
np.dtype([("r", np.ubyte),
        ("g", np.ubyte),
        ("b", np.ubyte),
        ("a", np.ubyte)])

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [41]:
np.dot(np.random.random((5,3)),np.random.random((3,2)))

array([[0.19203866, 0.46517392],
       [0.57004753, 1.00210842],
       [0.42337536, 0.66145538],
       [0.68792175, 1.16059719],
       [0.65013116, 1.00108382]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [61]:
array4 = np.random.random(10)*10
array4 = np.where((array4>3) & (array4<8),array4*-1, array4)
array4

array([ 1.47927405, -5.87359345, -4.96624283, -4.48889935, -3.88662441,
        9.20489134,  8.72029748,  0.31472039, -3.87041555, -7.72065144])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [62]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [65]:
Z = np.random.random(3)
print(Z**Z)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)

[0.81896573 0.71613592 0.69552988]
[False False False]
[0.+0.07847248j 0.+0.53699553j 0.+0.42887421j]
[0.07847248 0.53699553 0.42887421]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [68]:
np.array(0) / np.array(0) #error
np.array(0) // np.array(0) #error
np.array([np.nan]).astype(int).astype(float)

C:\Temp\ipykernel_19328\2512714816.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0) #error
C:\Temp\ipykernel_19328\2512714816.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0) #error


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [80]:
array5 = np.random.random(5)*10
np.round(array5)

array([0., 2., 2., 0., 7.])

#### 30. How to find common values between two arrays? (★☆☆)

In [82]:
array6_1 = np.random.random(10)*10
array6_2 = np.random.random(10)*10
array6_1 = np.round(array6_1)
array6_2 = np.round(array6_2)
array6_1, array6_2, np.intersect1d(array6_1,array6_2)

(array([2., 3., 2., 5., 6., 0., 3., 8., 7., 7.]),
 array([ 4.,  5., 10.,  1.,  8.,  4.,  9.,  4.,  0.,  0.]),
 array([0., 5., 8.]))

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [83]:
np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [84]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [89]:
np.datetime64('today')-1,np.datetime64('today'),np.datetime64('today')+1

(numpy.datetime64('2022-09-15'),
 numpy.datetime64('2022-09-16'),
 numpy.datetime64('2022-09-17'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)